add: kakao login & token validator
wecode-bootcamp-korea/39-2nd-stawefolio-backend pull request #7
Opened 2022-12-02 18:09 UTC by myeongseoklee

modify : app.js / server.js 분리
modify : unit test

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 카카오 소셜 로그인 기능
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 카카오 계정으로 로그인 시, 카카오 계정 정보와 데이터베이스의 유저정보(kakao id)를 비교, 일치 시 user의 id로 엑세스 토큰 발급
- 유저 정보가 없는 경우, 카카오 ID 토큰 내부정보를 활용하여 자동 회원가입 후 엑세스 토큰 발급
- 로그인 시 카카오id 중복문제 해결을 위한 kakaoid UNIQUE CONSTARAINT 추가 

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
<img width="1198" alt="스크린샷 2022-12-03 오전 2 42 16" src="https://user-images.githubusercontent.com/109528794/205357300-62ee6d08-d842-4286-8130-d37d0e7cd505.png">

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="620" alt="스크린샷 2022-12-03 오전 2 42 57" src="https://user-images.githubusercontent.com/109528794/205357406-6210ee8e-54d0-4975-97d7-6a537992f2e8.png">

3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
<img width="752" alt="스크린샷 2022-12-03 오전 2 43 31" src="https://user-images.githubusercontent.com/109528794/205357422-c17b3bad-7b79-474b-8d39-8b5f55c531a9.png">

4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
<img width="443" alt="스크린샷 2022-12-03 오전 3 07 27" src="https://user-images.githubusercontent.com/109528794/205357688-d59033f1-4361-4880-81bf-c786fb65e8b2.png">

<br />

## :: 기타 질문 및 특이 사항
- unit test시 service, dao단의 커버리지가 현저히 낮고, success test가 통과되지 않는데 원인을 모르겠습니다.

2022-12-05 03:36 UTC, Kang-kyunghun requested changes

2022-12-05 03:36 UTC, Kang-kyunghun commented on src/controllers/authController.js
> +
해당 로직은 controller보다는 service에 있는 것이 더 적절해 보입니다.
즉, 컨트롤러에서 1개의 service를 호출하여 해당 service에서 로직을 처리해 주세요.

2022-12-05 03:36 UTC, Kang-kyunghun commented on src/utils/tokenValidator.js
> +  return payload.id;
1. 해당 로직에서 실제 payload에서 받은 id가 우리 데이터베이스에 있는 User인지 판단하는 로직 추가해 주세요.
2. user 판단 후 request 객체에 user데이터를 추가해 주세요. 
미들웨어로 사용할 함수 아닌가요? 로직 판단 후 return이 아닌 next()로 다음 함수가 실행 되게 해주세요.

2022-12-05 04:24 UTC, myeongseoklee commented on src/controllers/authController.js
> +
해당부분 서비스 로직으로 처리 완료하였습니다.

2022-12-05 04:26 UTC, myeongseoklee commented on src/utils/tokenValidator.js
> +  return payload.id;
- 유저가 DB에 있는 유저인지 판단하는 로직을 추가했습니다. 페이로드에 kakao id 추가해서 기존에 활용하던 getUserByKakaoId 함수를 재활용했습니다.

- next 추가하였습니다.

세심하게 봐주셔서 감사드립니다!

2022-12-05 10:26 UTC, Kang-kyunghun requested changes

2022-12-05 10:26 UTC, Kang-kyunghun commented on src/models/authDao.js
> +    customError('Invalid Data Input', 500);
상태코드 500은 백엔드가 에러를 잡지 못 했을 때 주는 코드 입니다.
해당 상황은 에러르 처리한 것이므로 400으로 수정하면 좋을 것 같네요.
(만약 400이 아니고 더 적절한 코드가 있다고 판단되면 해당 상태코드로 바꾸셔도 됩니다.

2022-12-05 11:00 UTC, myeongseoklee commented on src/models/authDao.js
> +    customError('Invalid Data Input', 500);
어플리케이션 서버와 데이터베이스 서버 사이에서 발생한 오류이므로
Gateway Timeout을 의미하는 504 상태코드로 수정하였습니다.

2022-12-06 02:41 UTC, Kang-kyunghun commented on src/models/authDao.js
> +    customError('Invalid Data Input', 500);
504 에러는 서버 접속 자체가 지연 될 때 사용하는 에러 입니다. 디비 접속 시 에러가 날 수 도 있겠지만, 이런 경우는 초기화에서 걸러 질 것 같습니다. 따라서 500 때가 아닌 400 때에서 적절한 코드로 수정하면 좋을 것 같네요.

2022-12-06 03:30 UTC, myeongseoklee commented on src/models/authDao.js
> +    customError('Invalid Data Input', 500);
504 에러 코드에 대해 잘못 이해했던 것 같습니다 적절한 코드로 수정 후 라벨 달겠습니다!

2022-12-06 06:21 UTC, merged